-- Database schema for Recommendation System Microservice

-- Tabla para Tipos de Interacciones de Usuario con Productos
CREATE TABLE interaction_types (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla para Interacciones de Usuario con Productos
CREATE TABLE user_product_interactions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL UNIQUE,
    product_id INTEGER NOT NULL UNIQUE,
    interaction_type_id INTEGER NOT NULL REFERENCES interaction_types(id),
    interaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    score INTEGER CHECK (score BETWEEN 1 AND 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla para almacenar relaciones de similitud entre productos
CREATE TABLE product_similarities (
    product_id INTEGER NOT NULL UNIQUE,
    similar_product_id INTEGER NOT NULL UNIQUE,
    similarity_score DECIMAL(5,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (product_id, similar_product_id),
    CHECK (product_id != similar_product_id)
);
